var test = require('tape')
var u = require('../.')

test('methods should return path methods from openapi definition', function (t) {
  var api = require('./fixtures/api.json')
  // t.plan(6)
  var s = u.methods(api, '/animals/{par1}/cats', 'get')
  t.deepEqual(s, [ 'GET', 'PUT' ], '/animals/{par1}/cats')
  s = u.methods(api, '/animals/cats', 'get')
  t.deepEqual(s, [ 'GET' ], '/animals/cats')
  s = u.methods(api, '/animals/catsAndDogs', 'get')
  t.deepEqual(s, [ 'GET', 'POST' ], '/animals/catsAndDogs')
  s = u.methods(api, '/animals/{par1}/cats/{par2}')
  t.deepEqual(s, [ 'PATCH' ], '/animals/{par1}/cats/{par2}')
  s = u.methods(api, '/animals/{par1}/dogs/{par2}')
  t.deepEqual(s, [ 'GET', 'PUT', 'POST' ], '/animals/{par1}/dogs/{par2}')
  s = u.methods(api, '/animalz')
  t.deepEqual(s, [ ], '/animalz')
  t.end()
})
